name: ayah_share
description: "A new Flutter project to share Ayahs of Quran with friends."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_colorpicker: ^1.1.0
  screenshot: ^3.0.0
  firebase_core: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: IndoPak
      fonts:
        - asset: assets/fonts/indopak.ttf

    - family: Alvi
      fonts:
        - asset: assets/fonts/alvi.ttf